Support running tests locally
When running the tests locally (e.g. during Debian package build), the
binary `salt-factories` is not available in the search path yet.
Therefore `test_salt_factories_cli` will fail:

```
FileNotFoundError: [Errno 2] No such file or directory: 'salt-factories'
```

Check if `salt-factories` is missing but the entry point for the binary
is present locally. In thase fall back to use the local library.

Forwarded: https://github.com/saltstack/pytest-salt-factories/pull/59
Signed-off-by: Benjamin Drung <benjamin.drung@ionos.com>